export const menuItems = [
  // CAFÉS FRÍOS - Clásicos
  {
    id: 1,
    nombre: "Dalgona Coffee",
    descripcion: "Crema de café batida, leche fresca y canela.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/dalgona-coffee.png",
  },
  {
    id: 2,
    nombre: "Spanish Iced Latte",
    descripcion: "Doble espresso, leche condensada y leche fresca.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/spanish-iced-latte.png",
  },
  {
    id: 4,
    nombre: "Oreo Cream Latte",
    descripcion: "Doble espresso, crema de oreo, leche fresca, galletas oreo, sirope de vainilla.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/oreo-cream-latte.png",
  },
  {
    id: 5,
    nombre: "Oreo White Mocha",
    descripcion: "Doble espresso, leche fresca, sirope de chocolate blanco, cold foam de oreo.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/oreo-white-mocha.png",
  },
  {
    id: 6,
    nombre: "Salted Vanilla Iced Coffee",
    descripcion: "Espresso suave, agua, sirope de vainilla y vanilla cold foam.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/salted-vanilla-iced-coffee.png",
  },
  {
    id: 7,
    nombre: "Salted Caramel Iced Mocha",
    descripcion: "Espresso suave, leche fresca, sirope de chocolate y caramelo.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/salted-caramel-iced-mocha.png",
  },
  {
    id: 8,
    nombre: "Cinnamon Mocha Iced Latte",
    descripcion: "Doble espresso, leche fresca, canela, cacao en polvo y cold foam.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/cinnamon-mocha-iced-latte.png",
  },
  {
    id: 9,
    nombre: "Cinnamon Honey Latte",
    descripcion: "Espresso suave, leche fresca y honey cream.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/cinnamon-honey-latte.png",
  },
  {
    id: 10,
    nombre: "White Mocha Latte",
    descripcion: "Espresso suave, leche fresca y sirope de chocolate blanco.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/white-mocha-latte.png",
  },
  {
    id: 11,
    nombre: "Honey Cream Coffee",
    descripcion: "Crema de café con sirope de miel y leche fresca.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/honey-cream-coffee.png",
  },
  {
    id: 12,
    nombre: "Iced Caramel Macchiato",
    descripcion: "Doble espresso, leche fresca, sirope de vainilla, y sirope de caramelo.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/iced-caramel-macchiato.png",
  },
  {
    id: 13,
    nombre: "Peanut Butter Iced Latte",
    descripcion: "Espresso suave, leche fresca, crema de cacahuete, y miel.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/peanut-butter-iced-latte.png",
  },
  {
    id: 14,
    nombre: "Vanilla Brûlée Latte",
    descripcion: "Doble espresso, leche fresca, crema espumada de vainilla, y una fina capa caramelizada.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Clásicos",
    foto: "images/vanilla-brulee-latte.png",
  },

  // CAFÉS FRÍOS - Exóticos
  {
    id: 15,
    nombre: "Strawberry Iced Latte",
    descripcion: "Doble espresso, leche fresca, fresas, caramelo y cold foam.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Exóticos",
    foto: "images/strawberry-iced-latte.png",
  },
  {
    id: 16,
    nombre: "Banana Cream Iced Coffee",
    descripcion: "Doble espresso, leche fresca, plátano, miel, canela y agua.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Exóticos",
    foto: "images/banana-cream-iced-coffee.png",
  },
  {
    id: 17,
    nombre: "Orange Coffee",
    descripcion: "Doble espresso y zumo de naranja.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Exóticos",
    foto: "images/orange-coffee.png",
  },
  {
    id: 18,
    nombre: "Espresso Tonic",
    descripcion: "Espresso suave, agua tónica, y una tira de naranja.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Exóticos",
    foto: "images/espresso-tonic.png",
  },
  {
    id: 19,
    nombre: "Espresso Bomb",
    descripcion: "Doble espresso pasado por una rodaja de limon y un poco de sal y agua tónica.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Exóticos",
    foto: "images/espresso-bomb.png",
  },
  {
    id: 20,
    nombre: "Crema de Café Italiana",
    descripcion: "Crema de café y cacao en polvo.",
    categoria: "CAFÉS FRÍOS",
    subcategoria: "Exóticos",
    foto: "images/crema-de-cafe-italiana.png",
  },

  // CAFÉS CALIENTES
  {
    id: 21,
    nombre: "Café Bombón",
    descripcion: "Espresso suave, leche condensada y un toque de leche espumada.",
    categoria: "CAFÉS CALIENTES",
    foto: "images/cafe-bombon.png",
  },
  {
    id: 22,
    nombre: "Café con leche",
    descripcion: "Espresso suave y leche. (Hielo opcional)",
    categoria: "CAFÉS CALIENTES",
    foto: "images/cappuccino.png",
  },
  {
    id: 23,
    nombre: "Americano",
    descripcion: "Espresso suave y agua caliente.",
    categoria: "CAFÉS CALIENTES",
    foto: "images/americano.png",
  },
  {
    id: 24,
    nombre: "Mocha",
    descripcion: "Café con chocolate (leche, blanco, negro), leche y espuma.",
    categoria: "CAFÉS CALIENTES",
    foto: "images/mocha.png",
  },
  {
    id: 25,
    nombre: "Cappuccino",
    descripcion: "Espresso suave, leche, y abundante espuma.",
    categoria: "CAFÉS CALIENTES",
    foto: "images/cappuccino.png",
  },
  {
    id: 26,
    nombre: "Café Marocchino",
    descripcion: "Espresso suave, leche espumada, crema de cacao y cacao en polvo.",
    categoria: "CAFÉS CALIENTES",
    foto: "images/cafe-marocchino.png",
  },

  // OTRAS BEBIDAS
  {
    id: 27,
    nombre: "Matcha Latte",
    descripcion: "Matcha con leche caliente, leche fresca, miel, vainilla y caramelo.",
    categoria: "OTRAS BEBIDAS",
    foto: "images/matcha-latte.png",
  },
  {
    id: 28,
    nombre: "Frappé Especial",
    descripcion: "Frappé helado a elegir entre sabor Chocolate (negro/blanco/leche), kinder, Lotus o vainilla.",
    categoria: "OTRAS BEBIDAS",
    foto: "images/frappe-especial.png",
  },
  {
    id: 29,
    nombre: "Milkshakes",
    descripcion: "Batido cremoso con sabores a elegir: Vainilla, chocolate (negro/blanco/leche), oreo, caramelo, nocilla o lotus.",
    categoria: "OTRAS BEBIDAS",
    foto: "images/milkshake.png",
  },

  // APERITIVOS
  {
    id: 30,
    nombre: "Sándwich Mixto",
    descripcion: "Queso fundido, jamón york de primera calidad y mantequilla dorada al grill.",
    categoria: "APERITIVOS",
    foto: "images/sandwich-mixto.png",
  },
  {
    id: 31,
    nombre: "Croissant Mixto",
    descripcion: "Croissant de mantequilla relleno de queso fundido y jamón york.",
    categoria: "APERITIVOS",
    foto: "images/croissant-mixto.png",
  },
  {
    id: 32,
    nombre: "Tosta de Jamón y Tomate",
    descripcion: "Pan rústico tostado, jamón ibérico, tomate triturado (opcional) y aceite de oliva virgen extra.",
    categoria: "APERITIVOS",
    foto: "images/tosta-de-jamon-y-tomate.png",
  },
  {
    id: 33,
    nombre: "Tabla Variada",
    descripcion: "Selección de quesos curados, fuet, lomo embuchado y almendras tostadas.",
    categoria: "APERITIVOS",
    foto: "images/tabla-variada.png",
  },
  {
    id: 34,
    nombre: "Bizcocho Casero",
    descripcion: "Delicioso bizcocho artesano del día, esponjoso y aromático.",
    categoria: "APERITIVOS",
    foto: "images/bizcocho-casero.png",
  }
];
